version: '3.9'

services:
    database:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=rentx
        ports:
            - 5432:5432
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: rentx
        ports:
          - 3333:3333
        volumes:
            - .:/usr/app
        links: 
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local